-- CA PrepX — jobs board
-- Paste this whole file into Supabase → SQL Editor → New query → Run. Safe to run once.

create table if not exists public.jobs (
  id         bigint generated always as identity primary key,
  title      text not null,
  company    text not null,
  short      text,
  type       text,
  domain     text,
  city       text,
  location   text,
  stage      text[] not null default '{}',
  exp        text,
  apply      text not null,
  careers    text,
  email      text,
  source     text,
  seen       date not null default current_date,
  active     boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists jobs_seen_idx on public.jobs (seen desc);

alter table public.jobs enable row level security;

drop policy if exists "anyone reads active jobs" on public.jobs;
create policy "anyone reads active jobs" on public.jobs
  for select using (active or public.is_admin());

drop policy if exists "admin manages jobs" on public.jobs;
create policy "admin manages jobs" on public.jobs
  for all using (public.is_admin()) with check (public.is_admin());

grant select on public.jobs to anon, authenticated;
grant insert, update, delete on public.jobs to authenticated;

-- Openings checked on 27 Sep 2026
insert into public.jobs (title,company,short,type,domain,city,location,stage,exp,apply,careers,email,source,seen)
select title,company,short,type,domain,city,location,stage,exp,apply,careers,email,source,seen::date from (values
('Associate Consultant – Forensic Investigation (Assistant Manager)','Deloitte India','Deloitte','Big 4','forensic','delhi','Gurugram, Haryana',array['fresher']::text[],'CA freshers (Sept 2025 batch); statutory or internal audit exposure preferred','https://southasiacareers.deloitte.com/job/Gurugram-Assistant-Manager-Forensic-investigation-Gurugram-Forensic-&-Financial-Crime/59725044/','https://southasiacareers.deloitte.com/',null,'https://southasiacareers.deloitte.com/search/?q=CA&locationsearch=Gurugram','2026-09-13'),
('External Audit | Statutory Audit | Senior Assistant 1','Deloitte USI','Deloitte','Big 4','audit','delhi','Gurugram / Bengaluru / Hyderabad / Pune / Chennai / Kolkata',array['fresher']::text[],'Qualified CA, 0–1 year post-qualification','https://usijobs.deloitte.com/en_US/careersUSI/JobDetail/USI-EH-FY27-A-A-L35-Senior-Assistant-1-External-Audit/353084','https://usijobs.deloitte.com/',null,'https://usijobs.deloitte.com/en_US/careersUSI/SearchJobs/chartered%20accountant','2026-09-27'),
('Assistant Manager | TP Advisory, Compliance, APA & Controversy Management','Deloitte India','Deloitte','Big 4','dt','delhi','New Delhi, Delhi',array['fresher','exp']::text[],'CA qualified; 1–2 years in transfer pricing preferred','https://southasiacareers.deloitte.com/job/Delhi-Assistant-Manager-TP-Advisory%2C-Compliance%2C-APA-and-Controversy-management-Delhi-Transfer-Prici/60055144/','https://southasiacareers.deloitte.com/',null,'https://southasiacareers.deloitte.com/search/?q=tax&locationsearch=Delhi','2026-09-24'),
('Deputy Manager | Internal Audit','Deloitte India','Deloitte','Big 4','ia','delhi','New Delhi, Delhi',array['exp']::text[],'CA (or MBA/B.Com + CIA/CFE/CISA); 3–5 years post-qualification in internal audit','https://southasiacareers.deloitte.com/job/Delhi-Deputy-Manager-Internal-Audit-Delhi-Internal-Audit/60071444/','https://southasiacareers.deloitte.com/',null,'https://southasiacareers.deloitte.com/search/?q=audit+assurance&locationsearch=','2026-09-24'),
('Assistant Manager | Complex Securities Valuations','Deloitte India','Deloitte','Big 4','ta','delhi','New Delhi / Mumbai',array['exp']::text[],'CA / CFA, 3–6 years (1+ year in complex instrument valuation)','https://southasiacareers.deloitte.com/job/Delhi-Assistant-Manager-Complex-Securities-Valuations-Mumbai-Valuations-ICC/57970444/','https://southasiacareers.deloitte.com/',null,'https://southasiacareers.deloitte.com/search/?q=tax&locationsearch=Delhi','2026-09-13'),
('Consultant – Tax – Global Compliance & Reporting','EY India','EY','Big 4','dt','delhi','Gurugram, Haryana',array['exp']::text[],'CA / semi-qualified CA, 2–5 years','https://careers.ey.com/ey/job/Gurugram-Consultant-TAX-National-TAX-GCR-Global-Compliance-&-Reporting-Gurgaon-HR-122003/1429787133/','https://careers.ey.com/ey/search/',null,'https://careers.ey.com/ey/job/Gurugram-Consultant-TAX-National-TAX-GCR-Global-Compliance-&-Reporting-Gurgaon-HR-122003/1429787133/','2026-09-23'),
('Analyst – Tax – Global Compliance & Reporting','EY India','EY','Big 4','dt','delhi','Gurugram, Haryana',array['fresher','exp']::text[],'CA / semi-qualified CA, 0–4 years (tax litigation, tech interest)','https://careers.ey.com/ey/job/Gurugram-Analyst-TAX-National-TAX-GCR-Global-Compliance-&-Reporting-Gurgaon-HR-122003/1428095933/','https://careers.ey.com/ey/search/',null,'https://careers.ey.com/ey/job/Gurugram-Analyst-TAX-National-TAX-GCR-Global-Compliance-&-Reporting-Gurgaon-HR-122003/1428095933/','2026-08-20'),
('Assistant Manager – Assurance – FAAS (Financial & Accounting Advisory)','EY India','EY','Big 4','ctrl','delhi','Gurugram, Haryana',array['exp']::text[],'CA, 2–5 years','https://careers.ey.com/ey/job/Gurugram-Assistant-Manager-Assurance-National-ASU-FAAS-Financial&AccountingAdv-Gurgaon-HR-122003/1424954533/','https://careers.ey.com/ey/search/',null,'https://careers.ey.com/ey/job/Gurugram-Assistant-Manager-Assurance-National-ASU-FAAS-Financial&AccountingAdv-Gurgaon-HR-122003/1424954533/','2026-09-08'),
('Executive – Assurance – FAAS (Financial & Accounting Advisory)','EY India','EY','Big 4','ctrl','delhi','Gurugram, Haryana',array['exp']::text[],'CA, 1–3 years','https://careers.ey.com/ey/job/Gurugram-Executive-Assurance-National-ASU-FAAS-Financial&AccountingAdv-Gurgaon-HR-122003/1424960933/','https://careers.ey.com/ey/search/',null,'https://careers.ey.com/ey/job/Gurugram-Executive-Assurance-National-ASU-FAAS-Financial&AccountingAdv-Gurgaon-HR-122003/1424960933/','2026-09-08'),
('Associate – SaT – TCF – Financial Diligence (Consumer & Health)','EY India','EY','Big 4','ta','mumbai','Mumbai, Maharashtra',array['fresher']::text[],'Qualified CA, 0–1 year post-qualification','https://careers.ey.com/ey/job/Mumbai-Associate-SaT-CHS-SaT-TCF-Financial-Diligence-Mumbai-MH-400028/1439246933/','https://careers.ey.com/ey/search/',null,'https://careers.ey.com/ey/job/Mumbai-Associate-SaT-CHS-SaT-TCF-Financial-Diligence-Mumbai-MH-400028/1439246933/','2026-09-20'),
('Associate – SaT – TCF – Financial Diligence (AMI)','EY India','EY','Big 4','ta','mumbai','Mumbai, Maharashtra',array['exp']::text[],'CA, 1–8 years post-qualification','https://careers.ey.com/ey/job/Mumbai-Associate-SaT-AMI-SaT-TCF-Financial-Diligence-Mumbai-MH-400028/1431302033/','https://careers.ey.com/ey/search/',null,'https://careers.ey.com/ey/job/Mumbai-Associate-SaT-AMI-SaT-TCF-Financial-Diligence-Mumbai-MH-400028/1431302033/','2026-09-26'),
('Senior Associate – SaT – TCF – Financial Diligence','EY India','EY','Big 4','ta','mumbai','Mumbai, Maharashtra',array['exp']::text[],'CA, 1–8 years post-qualification','https://careers.ey.com/ey/job/Mumbai-Senior-Associate-SaT-CHS-SaT-TCF-Financial-Diligence-Mumbai-MH-400028/1438250233/','https://careers.ey.com/ey/search/',null,'https://careers.ey.com/ey/job/Mumbai-Senior-Associate-SaT-CHS-SaT-TCF-Financial-Diligence-Mumbai-MH-400028/1438250233/','2026-09-18'),
('Senior Consultant – Tax – Transfer Pricing (TMT)','EY India','EY','Big 4','dt','mumbai','Mumbai, Maharashtra',array['exp']::text[],'CA, 2–4 years core transfer pricing','https://careers.ey.com/ey/job/Mumbai-Senior-Consultant-TAX-TMT-TAX-ITTS-Transfer-Pricing-Mumbai-MH-400028/1428925533/','https://careers.ey.com/ey/search/',null,'https://careers.ey.com/ey/job/Mumbai-Senior-Consultant-TAX-TMT-TAX-ITTS-Transfer-Pricing-Mumbai-MH-400028/1428925533/','2026-09-20'),
('Executive – Assurance – FAAS (Financial & Accounting Advisory)','EY India','EY','Big 4','ctrl','mumbai','Mumbai, Maharashtra',array['exp']::text[],'CA, minimum 1 year; good Ind AS knowledge','https://careers.ey.com/ey/job/Mumbai-Executive-Assurance-National-ASU-FAAS-Financial&AccountingAdv-Mumbai-MH-400028/1427665833/','https://careers.ey.com/ey/search/',null,'https://careers.ey.com/ey/job/Mumbai-Executive-Assurance-National-ASU-FAAS-Financial&AccountingAdv-Mumbai-MH-400028/1427665833/','2026-08-18'),
('Consultant – Tax – Indirect Tax Core (TMT)','EY India','EY','Big 4','gst','bengaluru','Bengaluru, Karnataka',array['exp']::text[],'CA, 1+ year','https://careers.ey.com/ey/job/Bengaluru-Consultant-TAX-TMT-TAX-Indirect-Tax-Core-Bangalore-KA-560001/1438242633/','https://careers.ey.com/ey/search/',null,'https://careers.ey.com/ey/job/Bengaluru-Consultant-TAX-TMT-TAX-Indirect-Tax-Core-Bangalore-KA-560001/1438242633/','2026-09-18'),
('Senior Consultant – Tax – Global Compliance & Reporting (Tax Technology)','EY India','EY','Big 4','dt','bengaluru','Bengaluru, Karnataka',array['exp']::text[],'CA; tax technology background (years not stated)','https://careers.ey.com/ey/job/Bengaluru-Senior-Consultant-TAX-National-TAX-GCR-Global-Compliance-&-Reporting-Bangalore-KA-560001/1441327133/','https://careers.ey.com/ey/search/',null,'https://careers.ey.com/ey/job/Bengaluru-Senior-Consultant-TAX-National-TAX-GCR-Global-Compliance-&-Reporting-Bangalore-KA-560001/1441327133/','2026-09-25'),
('Assistant Manager | Accounting & Reporting Assurance','Deloitte India','Deloitte','Big 4','ctrl','bengaluru','Bengaluru, Karnataka',array['exp']::text[],'CA qualified or pursuing (or CFA/MBA), 3–5 years (fund / trust accounting)','https://southasiacareers.deloitte.com/job/Bengaluru-Assistant-Manager-Accounting-&-Reporting-Bengaluru-Accounting-&-Reporting-Assurance/60021244/','https://southasiacareers.deloitte.com/',null,'https://southasiacareers.deloitte.com/search/?q=audit+assurance&locationsearch=','2026-09-23'),
('Consultant – Tax – Global Compliance & Reporting','EY India','EY','Big 4','dt','pune','Pune, Maharashtra',array['exp']::text[],'CA + MBA, 1–2 years in tax/finance','https://careers.ey.com/ey/job/Pune-Consultant-TAX-National-TAX-GCR-Global-Compliance-&-Reporting-Pune-MH-411001/1439282533/','https://careers.ey.com/ey/search/',null,'https://careers.ey.com/ey/job/Pune-Consultant-TAX-National-TAX-GCR-Global-Compliance-&-Reporting-Pune-MH-411001/1439282533/','2026-09-21'),
('Consultant – Tax – Global Compliance & Reporting (TMT)','EY India','EY','Big 4','dt','hyderabad','Hyderabad, Telangana',array['fresher','exp']::text[],'CA, 0–2 years','https://careers.ey.com/ey/job/Hyderabad-Consultant-TAX-TMT-TAX-GCR-Global-Compliance-&-Reporting-Hyderabad-500032/1435429233/','https://careers.ey.com/ey/search/',null,'https://careers.ey.com/ey/job/Hyderabad-Consultant-TAX-TMT-TAX-GCR-Global-Compliance-&-Reporting-Hyderabad-500032/1435429233/','2026-09-09'),
('Analyst – Firm Tax – Indirect Tax (GST)','Deloitte USI','Deloitte','Big 4','gst','hyderabad','Hyderabad, Telangana',array['exp']::text[],'CA / CS / CMA / M.Com / LL.B., 1–2 years in GST (11am–8pm shift)','https://usijobs.deloitte.com/en_US/careersUSI/JobDetail/USI-EH27-Firm-Tax-Indirect-Tax-GST-L25-Analyst-Hyderabad/367673','https://usijobs.deloitte.com/',null,'https://usijobs.deloitte.com/en_US/careersUSI/SearchJobs/chartered%20accountant','2026-09-27'),
('Associate, India Controllers and Financial & Prudential Reporting','BlackRock','BlackRock','GCC / MNC','ctrl','delhi','Gurugram, Haryana',array['exp']::text[],'4+ yrs in financial services; CA preferred','https://in.indeed.com/viewjob?jk=a9ea5f4028b94b8d','https://careers.blackrock.com/location/gurgaon-jobs/45831/1269750-1270260-1270642/4',null,'https://in.indeed.com/viewjob?jk=a9ea5f4028b94b8d','2026-09-10'),
('Senior Associate - Indirect Tax (EMEA VAT)','Macquarie Group','Macquarie','Investment bank','gst','delhi','Gurugram, Haryana',array['fresher']::text[],'Newly qualified CA','https://in.indeed.com/viewjob?jk=8eeef4ef58e1c845','https://recruitment.macquarie.com/en_US/careers/SearchJobs/',null,'https://in.indeed.com/viewjob?jk=8eeef4ef58e1c845','2026-09-27'),
('Finance Analyst','Agilent Technologies','Agilent','GCC / MNC','fpa','delhi','Manesar, Gurugram, Haryana',array['exp']::text[],'CA with 1–3 yrs post-qualification (or CA Inter with 3–4 yrs)','https://agilent.wd5.myworkdayjobs.com/de-DE/Agilent_Careers/job/India-Manesar/Finance-Analyst_4038429/apply','https://agilent.wd5.myworkdayjobs.com/Agilent_Careers',null,'https://in.indeed.com/viewjob?jk=46f8e8480a6089ee','2026-09-27'),
('Hedge Accounting Analyst','Barclays','Barclays','Bank / NBFC','ctrl','delhi','Noida, Uttar Pradesh (Chennai option)',array['fresher','exp']::text[],'Must be a fully qualified accountant; years not stated','https://in.indeed.com/viewjob?jk=32840932e1a696f7','https://search.jobs.barclays/search-jobs/Noida,%20Uttar%20Pradesh/13015/4/1269750-1253626-9072784-7279746/28x58/77x33/50/2',null,'https://in.indeed.com/viewjob?jk=32840932e1a696f7','2026-09-23'),
('Impairment Analyst (IFRS 9 / ECL)','Barclays','Barclays','Bank / NBFC','ctrl','delhi','Noida / Gurugram',array['fresher','exp']::text[],'CA not mandatory; IFRS 9/ECL and banking exposure preferred','https://barclays.wd3.myworkdayjobs.com/External_Career_Site_Barclays/job/Noida-Candor-TechSpace/Impairment-Analyst_JR-0000120931-1/apply','https://search.jobs.barclays/search-jobs/Noida,%20Uttar%20Pradesh/13015/4/1269750-1253626-9072784-7279746/28x58/77x33/50/2',null,'https://search.jobs.barclays/job/noida/impairment-analyst/13015/99013666192','2026-08-24'),
('Manager – Business Finance (Lending)','Paytm','Paytm','Fintech','fpa','delhi','Noida, Uttar Pradesh',array['exp']::text[],'CA or top-tier MBA Finance; 4–5 yrs in business finance/FP&A','https://jobs.lever.co/paytm/837c89a3-3598-410c-a0a3-3af4927a42ed','https://jobs.lever.co/paytm',null,'https://jobs.lever.co/paytm','2026-09-27'),
('Senior Specialist 2, Internal Audit','MongoDB','MongoDB','GCC / MNC','ia','delhi','Gurugram, Haryana',array['exp']::text[],'CA required; 2+ yrs accounting/audit','https://in.indeed.com/viewjob?jk=ef4f765dcd0d4e78','https://www.mongodb.com/careers',null,'https://in.indeed.com/viewjob?jk=ef4f765dcd0d4e78','2026-09-27'),
('Sr. Specialist - F&A - FP&A','Genpact','Genpact','GCC / MNC','fpa','delhi','Gurugram, Haryana',array['exp']::text[],'Commerce/Finance degree; CA not required (CMA/CPA/CFA listed as pluses); years not stated','https://in.indeed.com/viewjob?jk=af12de26a8ad2081','https://genpact.wd108.myworkdayjobs.com/External_Careers',null,'https://in.indeed.com/viewjob?jk=af12de26a8ad2081','2026-09-27'),
('Corporate Internal Controls','Larsen & Toubro','L&T','Corporate','ia','mumbai','Powai, Mumbai',array['exp']::text[],'CA; 3–6 yrs','https://in.indeed.com/viewjob?jk=073ffa096d7b4c8d','https://www.larsentoubro.com/corporate/careers',null,'https://in.indeed.com/viewjob?jk=073ffa096d7b4c8d','2026-09-11'),
('Associate, M&A','Standard Chartered','Standard Chartered','Bank / NBFC','ib','mumbai','Mumbai',array['exp']::text[],'1–2 yrs banking/M&A/IB; postgraduate in Finance or Accountancy (CA not mandatory); closes 13 Oct 2026','https://in.indeed.com/viewjob?jk=3b5aaa26c2a51435','https://jobs.standardchartered.com/',null,'https://in.indeed.com/viewjob?jk=3b5aaa26c2a51435','2026-09-27'),
('Global Investment Banking Product Control - Associate','JPMorganChase','J.P. Morgan','Investment bank','ctrl','mumbai','Mumbai',array['exp']::text[],'Qualified or part-qualified accountant; 3+ yrs','https://in.indeed.com/viewjob?jk=ea93a4943fe17d64','https://careers.jpmorgan.com/in/en/about-us/locations/mumbai',null,'https://in.indeed.com/viewjob?jk=ea93a4943fe17d64','2026-09-27'),
('Manager – Taxation & Finance (Paytm Money)','Paytm','Paytm','Fintech','dt','mumbai','Mumbai',array['exp']::text[],'CA preferred; 4–8 yrs direct tax/GST/tax accounting','https://jobs.lever.co/paytm/3d3ee995-ba39-4d3a-95fd-ef391b7f3b58','https://jobs.lever.co/paytm',null,'https://jobs.lever.co/paytm','2026-09-27'),
('Finance Manager - Chartered Accountant','Cashflo','Cashflo','Fintech','ctrl','mumbai','Andheri East, Mumbai',array['exp']::text[],'CA (ICAI) mandatory; 1–2 yrs post-qualification','https://jobs.accaglobal.com/job/13019479/finance-manager-chartered-accountant-mumbai/',null,null,'https://in.indeed.com/viewjob?jk=fa341986f77a78ec','2026-09-27'),
('Internal Audit - Analyst - Business Audit','Goldman Sachs','Goldman Sachs','Investment bank','ia','bengaluru','Bengaluru',array['fresher','exp']::text[],'Qualified CA/CIA/CPA or equivalent; years not stated','https://higher.gs.com/roles/172075',null,null,'https://higher.gs.com/roles/172075','2026-09-27'),
('Finance Analyst (Chartered Accountant)','Millennium Management','Millennium','GCC / MNC','ctrl','bengaluru','Bengaluru',array['exp']::text[],'CA; 1–3 yrs post-qualification','https://in.indeed.com/viewjob?jk=75ca7ed6911d14bc','https://career.mlp.com/careers/bangalore',null,'https://in.indeed.com/viewjob?jk=75ca7ed6911d14bc','2026-09-27'),
('Chartered Accountant Freshers (Financial Reporting)','Manipal Hospitals','Manipal Hospitals','Corporate','ctrl','bengaluru','Old Airport Road, Bengaluru',array['fresher']::text[],'CA; 0–1 yr; Ind AS reporting; on-site','https://in.indeed.com/viewjob?jk=3173aa65d1aa5193','https://careers.manipalhospitals.com/index.html',null,'https://in.indeed.com/viewjob?jk=3173aa65d1aa5193','2026-09-27'),
('Global Internal Auditor','Schneider Electric','Schneider Electric','GCC / MNC','ia','bengaluru','Bengaluru',array['exp']::text[],'CA preferred (CIA/CISA a plus) or MBA/CMA; years not stated','https://in.indeed.com/viewjob?jk=9991c4da60f7e615','https://careers.se.com/',null,'https://in.indeed.com/viewjob?jk=9991c4da60f7e615','2026-09-27'),
('Controllership Accountant II (Lease Accounting)','AECOM','AECOM','GCC / MNC','ctrl','bengaluru','Bengaluru (hybrid)',array['exp']::text[],'CPA or equivalent qualification (CA fits); 3+ yrs, including 2 in leases','https://in.indeed.com/viewjob?jk=9d8de26a9bde6b0a','https://aecom.jobs/locations/bengaluru-ind/jobs/',null,'https://in.indeed.com/viewjob?jk=9d8de26a9bde6b0a','2026-09-27'),
('Specialist - Indirect Tax','Maersk','Maersk','GCC / MNC','gst','pune','Pune',array['exp']::text[],'CA with 1–3 yrs post-qualification (or semi-qualified/MBA with 4+ yrs)','https://in.indeed.com/viewjob?jk=f1ae2d7a68ef8126','https://www.maersk.com/careers/vacancies',null,'https://in.indeed.com/viewjob?jk=f1ae2d7a68ef8126','2026-09-27'),
('Assurance – External Audit – Senior Associate (Non-Financial Services)','PwC Middle East','PwC','Big 4','audit','dubai','Dubai, UAE',array['fresher','exp']::text[],'Senior Associate-level external audit experience at a Big 4 firm; CA/ACA/ACCA/CPA preferred','https://careers.pwc.com/job/Dubai-Assurance-External-Audit-Senior-Associate-Dubai-%28Non-Financial-Services%29/1438050733/','https://careers.pwc.com/search/?q=&locationsearch=Dubai',null,'https://careers.pwc.com/job/Dubai-Assurance-External-Audit-Senior-Associate-Dubai-%28Non-Financial-Services%29/1438050733/','2026-09-27'),
('Tax & Legal Services – Corporate Tax Advisory – Senior Associate','PwC Middle East','PwC','Big 4','dt','dubai','Dubai, UAE',array['exp']::text[],'Post-qualification corporate tax experience in a Big 4 or mid-tier firm; ACA/CTA or equivalent; UAE CT exposure an advantage','https://careers.pwc.com/job/Dubai-Tax-&-Legal-Services-Corporate-Tax-Advisory-Senior-Associate-%28Dubai%29/1372279333/','https://careers.pwc.com/search/?q=&locationsearch=Dubai',null,'https://careers.pwc.com/job/Dubai-Tax-&-Legal-Services-Corporate-Tax-Advisory-Senior-Associate-%28Dubai%29/1372279333/','2026-09-27'),
('Audit – Senior – IGH Audit','KPMG Lower Gulf','KPMG','Big 4','audit','dubai','Dubai, UAE',array['fresher','exp']::text[],'Senior level','https://jobs.accaglobal.com/job/14136274/audit-senior-igh-audit/','https://kpmg.com/ae/en/careers.html',null,'https://jobs.accaglobal.com/employer/00fe00b9-d1ad-4ebe-ae63-c824686c7673/kpmg-lower-gulf-limited','2026-09-27'),
('Audit – Senior – TMT Audits','KPMG Lower Gulf','KPMG','Big 4','audit','dubai','Dubai, UAE',array['fresher','exp']::text[],'Senior level','https://jobs.accaglobal.com/job/14127263/audit-senior-tmt-audits','https://kpmg.com/ae/en/careers.html',null,'https://jobs.accaglobal.com/employer/00fe00b9-d1ad-4ebe-ae63-c824686c7673/kpmg-lower-gulf-limited','2026-09-27'),
('Senior Consultant – Financial Services – ERS (GRC)','KPMG Lower Gulf','KPMG','Big 4','ia','dubai','Dubai, UAE',array['exp']::text[],'Senior Consultant level; closing soon','https://jobs.accaglobal.com/job/14109554/senior-consultant-financial-services-ers-grc-','https://kpmg.com/ae/en/careers.html',null,'https://jobs.accaglobal.com/employer/00fe00b9-d1ad-4ebe-ae63-c824686c7673/kpmg-lower-gulf-limited','2026-09-27'),
('Senior Associate – ERS (GRC – Telecom Sector Exp. Preferred)','KPMG Lower Gulf','KPMG','Big 4','ia','dubai','Dubai & Abu Dhabi, UAE',array['fresher','exp']::text[],'Senior Associate level; telecom exposure preferred','https://jobs.accaglobal.com/job/14136227/senior-associate-ers-grc-telecom-sector-exp-preferred-','https://kpmg.com/ae/en/careers.html',null,'https://jobs.accaglobal.com/employer/00fe00b9-d1ad-4ebe-ae63-c824686c7673/kpmg-lower-gulf-limited','2026-09-27'),
('Assistant Manager – Accounting and Finance','KPMG Lower Gulf','KPMG','Big 4','ctrl','dubai','Abu Dhabi, UAE',array['exp']::text[],'Assistant Manager level; closing soon','https://jobs.accaglobal.com/job/14109440/assistant-manager-accounting-and-finance','https://kpmg.com/ae/en/careers.html',null,'https://jobs.accaglobal.com/employer/00fe00b9-d1ad-4ebe-ae63-c824686c7673/kpmg-lower-gulf-limited','2026-09-27'),
('Experienced Senior Consultant / Assistant Manager – Transfer Pricing (Direct Tax)','Grant Thornton UAE','Grant Thornton','Mid-tier firm','dt','dubai','Abu Dhabi, UAE',array['exp']::text[],'4+ years in transfer pricing; CA/CPA/CFA/ACCA preferred','https://careers.grantthornton.ae/en/uae/jobs/experienced-senior-consultant-assistant-manager-transfer-pricing-direct-tax-1100020939/','https://careers.grantthornton.ae/','careers@ae.gt.com','https://careers.grantthornton.ae/en/uae/jobs/experienced-senior-consultant-assistant-manager-transfer-pricing-direct-tax-1100020939/','2026-09-25'),
('Senior Consultant – Internal Audit (Arabic Speaking) – Business Risk Services','Grant Thornton UAE','Grant Thornton','Mid-tier firm','ia','dubai','Abu Dhabi, UAE',array['exp']::text[],'3+ years IA/risk at an international consulting firm; CIA/ACCA/CA/CRMA preferred; English–Arabic bilingual mandatory','https://careers.grantthornton.ae/en/uae/jobs/senior-consultant-internal-audit-arabic-speaking-business-risk-services-1100020639/','https://careers.grantthornton.ae/','careers@ae.gt.com','https://careers.grantthornton.ae/en/uae/jobs/senior-consultant-internal-audit-arabic-speaking-business-risk-services-1100020639/','2026-08-31'),
('Manager – Financial Controlling','Al-Futtaim Group','Al-Futtaim','Corporate','ctrl','dubai','Dubai, UAE',array['exp']::text[],'Manager level','https://jobs.accaglobal.com/job/14151192/manager-financial-controlling',null,null,'https://jobs.accaglobal.com/employer/c6e52481-f840-4584-9e36-3f21d07e6a90/al-futtaim-group','2026-09-27'),
('FP&A Manager – Real Estate / Contracting','Al-Futtaim Group','Al-Futtaim','Corporate','fpa','dubai','Dubai, UAE',array['exp']::text[],'Manager level','https://jobs.accaglobal.com/job/14148344/fp-and-a-manager-i-real-estate-i-contracting',null,null,'https://jobs.accaglobal.com/employer/c6e52481-f840-4584-9e36-3f21d07e6a90/al-futtaim-group','2026-09-27'),
('CA Article Trainee – FS Deals Tax','PwC India','PwC','Big 4','articleship','mumbai','Mumbai, Maharashtra',array['student']::text[],'CA Intermediate, both groups cleared; apply by email (details on the listing)','https://buddingca.com/ca-article-trainee-at-pwc-mumbai-fs-deals-tax/','https://www.pwc.in/careers.html',null,'https://buddingca.com/ca-article-trainee-at-pwc-mumbai-fs-deals-tax/','2026-09-11'),
('CA Article Trainee (Direct Tax, GST, Advisory)','S R Bagai & Co.','S R Bagai','Mid-tier firm','articleship','delhi','North Delhi, New Delhi',array['student']::text[],'CA Intermediate; stipend ₹1.5–3 LPA','https://www.caclubindia.com/jobs/ca-article-trainee-22384.asp',null,null,'https://www.caclubindia.com/jobs/ca-article-trainee-22384.asp','2026-09-16'),
('Article Assistant (Income Tax, GST, Audit)','Manuj Sharma & Company','Manuj Sharma & Company','Mid-tier firm','articleship','delhi','Noida, Uttar Pradesh (hybrid)',array['student']::text[],'CA Intermediate, fresher','https://www.caclubindia.com/jobs/article-assistant-22382.asp',null,null,'https://www.caclubindia.com/jobs/article-assistant-22382.asp','2026-09-16'),
('CA Article Assistant (Statutory/Internal/Bank Audit, Tax)','Ghosh Khanna & Co. LLP','Ghosh Khanna','Mid-tier firm','articleship','delhi','Gurugram, Haryana',array['student']::text[],'Fresh articleship aspirants; own laptop required; ₹8,000/month + conveyance','https://buddingca.com/ca-article-assistant-at-ghosh-khanna-co-llp-gurgaon/',null,null,'https://buddingca.com/ca-article-assistant-at-ghosh-khanna-co-llp-gurgaon/','2026-09-08'),
('Article Trainees (and CA Freshers)','Doogar & Associates','Doogar & Associates','Mid-tier firm','articleship','delhi','Gurugram, Haryana (also Udaipur)',array['student']::text[],'Articleship-eligible CA students; audit, tax, valuation, consulting','https://buddingca.com/ca-fresher-article-trainees-at-doogar-associates-gurgaon-udaipur/',null,null,'https://buddingca.com/ca-fresher-article-trainees-at-doogar-associates-gurgaon-udaipur/','2026-09-08'),
('Article Assistant','SGNG & Associates','SGNG & Associates','Mid-tier firm','articleship','delhi','New Delhi',array['student']::text[],'CA Intermediate','https://www.caclubindia.com/jobs/article-assistant-22368.asp',null,null,'https://www.caclubindia.com/jobs/browse.asp?city_id=&ccc_function_id=14&ccc_quali_id=','2026-09-01'),
('CA Industrial Trainee (Financial Reporting, Budgeting, Tax)','SAEL Industries Limited','SAEL Industries Limited','Corporate','articleship','delhi','Gurugram, Haryana',array['student']::text[],'CA students eligible for industrial training under ICAI rules; 1-year term; apply by email (details on the listing)','https://buddingca.com/ca-industrial-trainee-at-sael-industries-limited-gurugram/',null,null,'https://buddingca.com/ca-industrial-trainee-at-sael-industries-limited-gurugram/','2026-09-12'),
('Industrial Trainee (Accounting, Finance, Tax Compliance)','HUMBEE','HUMBEE','Corporate','articleship','delhi','Noida, Uttar Pradesh',array['student']::text[],'CA Intermediate; on-site','https://www.caclubindia.com/jobs/industrial-trainee-22387.asp',null,null,'https://www.caclubindia.com/jobs/industrial-trainee-22387.asp','2026-09-18'),
('Articles','Saini Pati Shah & Co LLP','Saini Pati Shah & Co','Mid-tier firm','articleship','mumbai','Mumbai, Maharashtra',array['student']::text[],'CA Intermediate','https://www.caclubindia.com/jobs/articles-22367.asp',null,null,'https://www.caclubindia.com/jobs/browse.asp?city_id=&ccc_function_id=14&ccc_quali_id=','2026-09-01'),
('Article / Paid Assistant','Murali and Sumeet','Murali and Sumeet','Mid-tier firm','articleship','bengaluru','Bengaluru, Karnataka',array['student']::text[],'CA Intermediate','https://www.caclubindia.com/jobs/article-paid-assistant-22371.asp',null,null,'https://www.caclubindia.com/jobs/browse.asp?city_id=&ccc_function_id=14&ccc_quali_id=','2026-09-07')
) as v(title,company,short,type,domain,city,location,stage,exp,apply,careers,email,source,seen)
where not exists (select 1 from public.jobs);
